source:
  url_endpoint: https://cds.climate.copernicus.eu/api/v2
  key: 81948:eb272f3a-4ca5-49e3-855a-2e384b0af27d
  nc_files: /data/wrfout_d02_*
  # nc_files: /media/sdb1/Data/UC/wrf/wrfout_d02_*
  chunks: 30
  start: '2017-01-01'
  end: '2020-12-31'
  time_interval: Y
  public_url: https://b2.nzrivers.xyz
  dataset_metadata:
    product_code: NZ South Island 9km v01
    owner: NZ Open Modelling Consortium
    license: https://creativecommons.org/licenses/by/4.0/
    attribution: Data licensed by the NZ Open Data Consortium
    run_date: '2021-01-01'
  # datasets: [precip_at_0, reference_et]
  datasets: [precip_at_0, temp_at_2, snow_at_0, relative_humidity_at_2, wind_speed_at_2, reference_et]

remote:
  email:
    sender_address: noreply@tethys-ts.xyz
    sender_password: tethys-bot
    receiver_address: mullenkamp1@gmail.com
    smtp_server: mail.tethys-ts.xyz
  s3:
    connection_config:
      service_name: 's3'
      endpoint_url: https://s3.us-west-000.backblazeb2.com
      aws_access_key_id: 000f9ba625c1c3c0000000001
      aws_secret_access_key: K000p0QMmmDTSdE2gFRyU3R68K24No8
    bucket: nz-open-modelling-consortium
